services:
  ci:
    image: ${CI_IMAGE}
    container_name: ${CI_CONTAINER}
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint:
      - sleep
      - infinity
